-- =====================================================
-- Base de données Tbc Groupe - Version Supabase (PostgreSQL)
-- Converted from MySQL Schema
-- =====================================================
-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- =====================================================
-- ENUMS & TYPES
-- =====================================================
DO $$ BEGIN CREATE TYPE user_role AS ENUM ('super_admin', 'admin', 'editor');
EXCEPTION
WHEN duplicate_object THEN null;
END $$;
-- =====================================================
-- FUNCTIONS
-- =====================================================
-- Function to handle auto-updating updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ language 'plpgsql';
-- =====================================================
-- Table: users (Utilisateurs/Administrateurs)
-- =====================================================
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role user_role DEFAULT 'editor',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ NULL
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);
CREATE TRIGGER update_users_updated_at BEFORE
UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- =====================================================
-- Table: trainers (Formateurs)
-- =====================================================
CREATE TABLE IF NOT EXISTS trainers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT NOT NULL,
    bio TEXT NOT NULL,
    bio_extended TEXT,
    image_url TEXT,
    image_base64 TEXT,
    email TEXT,
    phone TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    display_order INTEGER DEFAULT 0,
    created_by INTEGER REFERENCES users(id) ON DELETE
    SET NULL,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_trainers_is_active ON trainers (is_active);
CREATE INDEX IF NOT EXISTS idx_trainers_display_order ON trainers (display_order);
CREATE INDEX IF NOT EXISTS idx_trainers_active_order ON trainers (is_active, display_order);
CREATE TRIGGER update_trainers_updated_at BEFORE
UPDATE ON trainers FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- =====================================================
-- Table: trainer_experiences (Expériences des formateurs)
-- =====================================================
CREATE TABLE IF NOT EXISTS trainer_experiences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id INTEGER NOT NULL REFERENCES trainers(id) ON DELETE CASCADE,
    year TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_trainer_exp_trainer_id ON trainer_experiences (trainer_id);
CREATE INDEX IF NOT EXISTS idx_trainer_exp_display_order ON trainer_experiences (display_order);
-- =====================================================
-- Table: trainer_skills (Compétences des formateurs)
-- =====================================================
CREATE TABLE IF NOT EXISTS trainer_skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id INTEGER NOT NULL REFERENCES trainers(id) ON DELETE CASCADE,
    skill_name TEXT NOT NULL,
    skill_level INTEGER NOT NULL CHECK (
        skill_level >= 0
        AND skill_level <= 100
    ),
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_trainer_skills_trainer_id ON trainer_skills (trainer_id);
CREATE INDEX IF NOT EXISTS idx_trainer_skills_display_order ON trainer_skills (display_order);
-- =====================================================
-- Table: trainer_technologies (Technologies maîtrisées)
-- =====================================================
CREATE TABLE IF NOT EXISTS trainer_technologies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id INTEGER NOT NULL REFERENCES trainers(id) ON DELETE CASCADE,
    technology_name TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_trainer_tech_trainer_id ON trainer_technologies (trainer_id);
CREATE INDEX IF NOT EXISTS idx_trainer_tech_display_order ON trainer_technologies (display_order);
-- =====================================================
-- Table: services (Services de l'entreprise)
-- =====================================================
CREATE TABLE IF NOT EXISTS services (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon_name TEXT,
    features JSONB,
    technologies JSONB,
    is_active BOOLEAN DEFAULT TRUE,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_services_is_active ON services (is_active);
CREATE INDEX IF NOT EXISTS idx_services_display_order ON services (display_order);
CREATE INDEX IF NOT EXISTS idx_services_active_order ON services (is_active, display_order);
CREATE TRIGGER update_services_updated_at BEFORE
UPDATE ON services FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- =====================================================
-- Table: portfolio_projects (Projets du portfolio)
-- =====================================================
CREATE TABLE IF NOT EXISTS portfolio_projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT,
    image_base64 TEXT,
    technologies JSONB,
    project_url TEXT,
    github_url TEXT,
    category TEXT,
    is_featured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_projects_is_active ON portfolio_projects (is_active);
CREATE INDEX IF NOT EXISTS idx_projects_is_featured ON portfolio_projects (is_featured);
CREATE INDEX IF NOT EXISTS idx_projects_category ON portfolio_projects (category);
CREATE INDEX IF NOT EXISTS idx_projects_display_order ON portfolio_projects (display_order);
CREATE INDEX IF NOT EXISTS idx_projects_active_featured ON portfolio_projects (is_active, is_featured);
CREATE TRIGGER update_projects_updated_at BEFORE
UPDATE ON portfolio_projects FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- =====================================================
-- Table: contact_messages (Messages de contact)
-- =====================================================
CREATE TABLE IF NOT EXISTS contact_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    subject TEXT,
    phone TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMPTZ NULL,
    read_by INTEGER REFERENCES users(id) ON DELETE
    SET NULL,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_messages_email ON contact_messages (email);
CREATE INDEX IF NOT EXISTS idx_messages_is_read ON contact_messages (is_read);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON contact_messages (created_at);
-- =====================================================
-- Table: site_settings (Paramètres du site)
-- =====================================================
CREATE TABLE IF NOT EXISTS site_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key TEXT UNIQUE NOT NULL,
    setting_value TEXT,
    setting_type TEXT DEFAULT 'text',
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_settings_key ON site_settings (setting_key);
CREATE TRIGGER update_settings_updated_at BEFORE
UPDATE ON site_settings FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- =====================================================
-- Table: training_programs (Programmes de formation)
-- =====================================================
CREATE TABLE IF NOT EXISTS training_programs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id INTEGER REFERENCES trainers(id) ON DELETE
    SET NULL,
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        duration TEXT,
        price DECIMAL(10, 2),
        icon_name TEXT,
        is_active BOOLEAN DEFAULT TRUE,
        display_order INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_programs_trainer_id ON training_programs (trainer_id);
CREATE INDEX IF NOT EXISTS idx_programs_is_active ON training_programs (is_active);
CREATE INDEX IF NOT EXISTS idx_programs_display_order ON training_programs (display_order);
CREATE TRIGGER update_programs_updated_at BEFORE
UPDATE ON training_programs FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- =====================================================
-- VIEWS
-- =====================================================
-- View: v_trainers_details
CREATE OR REPLACE VIEW v_trainers_details AS
SELECT t.id,
    t.name,
    t.title,
    t.bio,
    t.bio_extended,
    t.image_url,
    t.image_base64,
    t.email,
    t.phone,
    t.is_active,
    t.display_order,
    COUNT(DISTINCT te.id) as experiences_count,
    COUNT(DISTINCT ts.id) as skills_count,
    COUNT(DISTINCT tt.id) as technologies_count,
    t.created_at,
    t.updated_at
FROM trainers t
    LEFT JOIN trainer_experiences te ON t.id = te.trainer_id
    LEFT JOIN trainer_skills ts ON t.id = ts.trainer_id
    LEFT JOIN trainer_technologies tt ON t.id = tt.trainer_id
WHERE t.is_active = TRUE
GROUP BY t.id,
    t.name,
    t.title,
    t.bio,
    t.bio_extended,
    t.image_url,
    t.image_base64,
    t.email,
    t.phone,
    t.is_active,
    t.display_order,
    t.created_at,
    t.updated_at;
-- View: v_unread_messages
CREATE OR REPLACE VIEW v_unread_messages AS
SELECT cm.*,
    u.full_name as read_by_name
FROM contact_messages cm
    LEFT JOIN users u ON cm.read_by = u.id
WHERE cm.is_read = FALSE
ORDER BY cm.created_at DESC;
-- =====================================================
-- STORED PROCEDURES (Functions in Postgres)
-- =====================================================
-- Procedure: sp_mark_message_read
CREATE OR REPLACE FUNCTION sp_mark_message_read(p_message_id INTEGER, p_user_id INTEGER) RETURNS VOID AS $$ BEGIN
UPDATE contact_messages
SET is_read = TRUE,
    read_at = CURRENT_TIMESTAMP,
    read_by = p_user_id
WHERE id = p_message_id;
END;
$$ LANGUAGE plpgsql;
-- Procedure: sp_get_site_stats
CREATE OR REPLACE FUNCTION sp_get_site_stats() RETURNS TABLE (
        active_trainers BIGINT,
        active_services BIGINT,
        active_projects BIGINT,
        unread_messages BIGINT,
        total_messages BIGINT
    ) AS $$ BEGIN RETURN QUERY
SELECT (
        SELECT COUNT(*)
        FROM trainers
        WHERE is_active = TRUE
    ) as active_trainers,
    (
        SELECT COUNT(*)
        FROM services
        WHERE is_active = TRUE
    ) as active_services,
    (
        SELECT COUNT(*)
        FROM portfolio_projects
        WHERE is_active = TRUE
    ) as active_projects,
    (
        SELECT COUNT(*)
        FROM contact_messages
        WHERE is_read = FALSE
    ) as unread_messages,
    (
        SELECT COUNT(*)
        FROM contact_messages
    ) as total_messages;
END;
$$ LANGUAGE plpgsql;
-- =====================================================
-- DATA INSERTION
-- =====================================================
-- Insert default admin user
INSERT INTO users (email, password_hash, full_name, role, is_active)
VALUES (
        'thibauttbcbujiriri@gmail.com',
        '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
        'Thibaut Tbc Bujiriri',
        'admin',
        TRUE
    ) ON CONFLICT (email) DO
UPDATE
SET email = EXCLUDED.email;
-- Insert site settings
INSERT INTO site_settings (
        setting_key,
        setting_value,
        setting_type,
        description
    )
VALUES (
        'company_name',
        'Tbc Groupe',
        'text',
        'Nom de l''entreprise'
    ),
    (
        'company_email',
        'thibauttbcbujiriri@gmail.com',
        'email',
        'Email principal de l''entreprise'
    ),
    (
        'company_phone',
        '+243 979 823 604',
        'text',
        'Téléphone principal'
    ),
    (
        'company_address',
        'Office 2 – Kanisa La Mungu, Goma, Nord-Kivu',
        'text',
        'Adresse complète'
    ),
    ('company_city', 'Goma', 'text', 'Ville'),
    (
        'company_region',
        'Nord-Kivu',
        'text',
        'Province/Région'
    ),
    (
        'company_country',
        'République Démocratique du Congo',
        'text',
        'Pays'
    ),
    (
        'company_description',
        'Expert en développement d''applications web et mobile, référencement SEO et formations en développement web et mobile. Spécialisé en environnement JavaScript.',
        'textarea',
        'Description de l''entreprise'
    ),
    (
        'site_title',
        'Tbc Groupe - Développement Web & Mobile | Formations JavaScript',
        'text',
        'Titre du site'
    ),
    (
        'site_description',
        'Expert en développement d''applications web et mobile, référencement SEO et formations. Spécialisé en environnement JavaScript.',
        'textarea',
        'Description SEO du site'
    ) ON CONFLICT (setting_key) DO
UPDATE
SET setting_value = EXCLUDED.setting_value,
    setting_type = EXCLUDED.setting_type,
    description = EXCLUDED.description;
-- Insert services
INSERT INTO services (
        title,
        description,
        icon_name,
        features,
        technologies,
        is_active,
        display_order
    )
VALUES (
        'Développement Web',
        'Applications web modernes et performantes avec React, Node.js et les dernières technologies JavaScript.',
        'Code',
        '["Applications web responsives", "Intégration d''APIs", "Optimisation des performances", "Maintenance et support"]'::jsonb,
        '["React", "Node.js", "TypeScript", "Next.js", "Express"]'::jsonb,
        TRUE,
        1
    ),
    (
        'Développement Mobile',
        'Applications mobiles cross-platform et natives pour iOS et Android.',
        'Smartphone',
        '["Applications iOS et Android", "Développement cross-platform", "Intégration de services cloud", "Publication sur les stores"]'::jsonb,
        '["React Native", "Flutter", "Swift", "Kotlin"]'::jsonb,
        TRUE,
        2
    ),
    (
        'Référencement SEO',
        'Optimisation pour les moteurs de recherche et amélioration de votre visibilité en ligne.',
        'Search',
        '["Audit SEO complet", "Optimisation du contenu", "Stratégie de link building", "Suivi et rapports d''analyse"]'::jsonb,
        '["Google Analytics", "Google Search Console", "Ahrefs", "SEMrush"]'::jsonb,
        TRUE,
        3
    ),
    (
        'Formations',
        'Formations complètes en développement web et mobile, spécialisées en environnement JavaScript.',
        'GraduationCap',
        '["Formations adaptées à tous les niveaux", "Programmes pratiques avec projets réels", "Support et suivi personnalisé", "Certification en fin de formation"]'::jsonb,
        '["JavaScript", "React", "Node.js", "React Native", "TypeScript"]'::jsonb,
        TRUE,
        4
    ) -- No generic unique key on title, so handling duplicates might differ. 
    -- In the original SQL it was ON DUPLICATE KEY UPDATE title=title (which does nothing).
    -- Here we can verify if we want to allow duplicates. Services usually have unique titles?
    -- Let's leave it as insert. If strict idempotency is needed, we'd need a unique constraint on title.
    -- For now, following the original logic of insertion.
;